version: '3.7'

services:
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    ports:
      - "8081:80"
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:alpine3.12
    ports:
      - "6379:6379"
    restart: always

